name: skillfloor_lms
description: Skillfloor LMS.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  http: ^1.1.0
  shared_preferences: ^2.0.15
  json_serializable: ^6.3.1
  fluttertoast: ^8.0.9
  cached_network_image: ^3.2.1
  share: ^2.0.4
  flutter_staggered_grid_view: ^0.6.2
  percent_indicator: ^4.2.2
  material_design_icons_flutter: ^6.0.7096
  image_picker: ^0.8.5+3
  url_launcher: ^6.1.5
  intl: ^0.18.0
  sqflite: ^2.0.3
  path_provider: ^2.0.11
  path: ^1.8.3
  connectivity_plus: ^3.0.3
  html_unescape: ^2.0.0
  universal_html: ^2.0.8
  pod_player: ^0.2.1
  webview_flutter: ^4.0.6
  background_downloader: ^7.10.0
  logging: ^1.2.0
  rename: ^3.0.2

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/splash.png
    - assets/images/login_forget.png
    - assets/images/do_login.png
    - assets/images/long_arrow_right.png
    - assets/images/loading_animated.gif
    - assets/images/play.png
    - assets/images/no_connection.png


  fonts:
    - family: google_sans
      fonts:
        - asset: assets/fonts/google_sans_regular.ttf
        - asset: assets/fonts/google_sans_bold.ttf
          weight: 700
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
